### ISSUE TITLE
Bug - Discord link is broken

### ISSUE THREAD

**Issue by bordumb** [DevNode-Dev/devnode-website#2]
## Overview

Steps to replicate:
1. Click on `Connect with Discord bot`
2. Click on `Go to Discord Server` 

Problem:
If you right-click this button in step 2, it's using a broken link pointing to `https://devnode-web-staging.up.railway.app/undefined` and throws the error below on the right.

![image](https://user-images.githubusercontent.com/3743841/212538448-b9772f43-ac7c-4183-af02-3cd0bcd2ba19.png)

Proposal:
Fix this link to directly open the Discord app on DevNode's server

**Comment by rushidhanwant** [comment]
resolved
