### ISSUE TITLE
UI/UX - Discord link missing

### ISSUE THREAD

**Issue by bordumb** [DevNode-Dev/devnode-website#3]
## Overview

The text below doesn't help users. If we tell a user to do something, we should guide them in 100% of cases.

<img width="848" alt="Screenshot 2023-01-15 at 11 37 40" src="https://user-images.githubusercontent.com/3743841/212538606-7b0e4675-0a8f-48b5-a74a-478949b487aa.png">

## Proposal

Add a link here that opens the same UX flow as what happens with "Connect with Discord bot" in the upper-right of the site

**Comment by rushidhanwant** [comment]
If you will click on `Please connect to Discord` text, Modal will open

**Comment by bordumb** [comment]
@rushidhanwant 

This is not how it works on my end.

In video below, all it does is highlight the text. There is no hyperlink present.

https://user-images.githubusercontent.com/3743841/212726143-13c77498-8dec-4b07-b0c8-5df41ce2def1.mov
