### ISSUE TITLE
UI/UX - Logo should link to homepage 

### ISSUE THREAD

**Issue by bordumb** [DevNode-Dev/devnode-website#4]
## Overview

The placeholder logo doesn't link to anything. 

It's pretty standard to let users click on the logo to link back to the homepage.

<img width="228" alt="Screenshot 2023-01-15 at 11 36 11" src="https://user-images.githubusercontent.com/3743841/212538653-7eb63d1c-94f9-4151-a300-dd6411a25fe2.png">

**Comment by rushidhanwant** [comment]
resolved
