### ISSUE TITLE
Bug - Discord doesn't connect

### ISSUE THREAD

**Issue by bordumb** [DevNode-Dev/devnode-website#5]
## Overview

Steps to reproduce

1. Click on `Connect with Discord Bot` -> Copy `DID` code 
2. Go to Discord server -> type `devnode` -> Paste `DID` code -> Copy Challenge Code 
3. Enter Challenge Link into Browser 
4. Problem: Discord doesn't appear connected 

See below:

![image](https://user-images.githubusercontent.com/3743841/212539038-03da6e8d-1047-4dc5-a985-6245b3c79b23.png)

## Blocking

This is blocking the following portions of Milestone 1:

add question | add question flow with question, technology tags
-- | --
question page | page that shows questions and answers
add answer | input answer and submit

**Comment by rushidhanwant** [comment]
Resolved
