### ISSUE TITLE
UI/UX - challenge code or challenge link?

### ISSUE THREAD

**Issue by bordumb** [DevNode-Dev/devnode-website#6]
## Overview

The app calls it a "challenge code", but Discord calls it a "challenge link"

For new users who are trying to follow closely, this can be confusing.

## Proposal

Pick a single term -> avoid confusion. I'd prefer "Challenge Link" as "Link" explicitly tells them it is the entire URL that is needed and not just the "code" at the end.

I might also add capitalisation (i.e. "Challenge Link") to show users that it is an important key term

**Comment by rushidhanwant** [comment]
changed name `challenge Link` to `challenge code` in the modal
